### ISSUE TITLE
rerun all on success

### ISSUE THREAD

**Issue by mwotton** [ocharles/tasty-rerun#13]
I tend to use hspec's rerun functionality to repeat failing tests until they pass. It will then run the whole test suite to see if I've broken other things in my enthusiasm. Is there a way to replicate this with tasty-rerun? I'm using `--rerun-update --rerun-filter=failures,exceptions`, and once that gets to zero failing tests, it just runs zero tests forever and i have to kill ghcid, remove the file and start again.

**Comment by Bodigrim** [comment]
Would a new command-line option `--rerun-all-if-empty`, which reruns everything whenever the log file contains 0 entries, suffice?

**Comment by Bodigrim** [comment]
Mode "rerun everything if the log file is empty" appeared to be inconvenient, because it takes an additional, non-productive execution of a test suite before rerunning everything. I decided in favor of `--rerun-all-on-success` with the semantics "if there is nothing to do, run everything".

**Comment by mwotton** [comment]
:bowing_man: thank you @Bodigrim, this is great.
