### ISSUE TITLE
--rerun-filter last

### ISSUE THREAD

**Issue by dontdieych** [ocharles/tasty-rerun#3]
Thanks for developing this package. Very helpful.

I'm haskell newbie doing on haskell 99 problems. I've wrote all code in one Main.hs file.

```
prop_f = ...

f = ...

prop_g = ...

g = ...

... [same pattern repeating] ...
```

Continuously changing between '--rerun-update' and '--rerun-filter failures,new' is a little bit annoying.  Now I'm just using '--pattern' option for current focused function. So I thought it would be quite handy if I could do '--rerun-update last'.

Thanks.

**Comment by Bodigrim** [comment]
I would prefer to avoid changing/extending syntax/semantics of existing options.

I think `--rerun-update --rerun-filter failures,exceptions --rerun-all-on-success` should help. Closing, but feel free to continue this discussion in #13.
