### ISSUE TITLE
tasty-rerun drops the -j parallel execution option?

### ISSUE THREAD

**Issue by paraseba** [ocharles/tasty-rerun#6]
I followed the instructions and I have all the --rerun- options working, but I lost the -j option. Am I doing something wrong or is that option not supported by rerun?

**Comment by ocharles** [comment]
I don't think you're doing anything wrong - I can't think of a reason that shouldn't work. Will try and look into it!

**Comment by paraseba** [comment]
If it helps:

```haskell
main :: IO ()
main = defaultMainWithIngredients
         defaultIngredients
         --[rerunningTests defaultIngredients]
         tests
```

Like that I get working -j option, but obviously no --rerun options. If I switch to the commented code instead of directly `defaultIngredients` I get working --rerun but no -j

**Comment by ocharles** [comment]
When you say it drops the flag, how are you coming to that conclusion? Do tests take significantly longer to evaluate?

**Comment by paraseba** [comment]
@ocharles --help doesn't report the option and if you try to pass the option you get an unknown option error

**Comment by Bodigrim** [comment]
It is fixed now.
