### ISSUE TITLE
improve --rerun-* descriptions

### ISSUE THREAD

**Issue by joeyh** [ocharles/tasty-rerun#8]
The descriptions for the --rerun-\* options that appear in --help output are often confusing to me. I typically have to go read the cabal file's descriptions of these options to remember how to use them.

--rerun-log-file ARG     The path to which rerun's state file should be saved

I often forget that there's a default rerun log file, and think I need to specify this option.
Saying what the default is would prevent this confusion.

I also often read this as meaning that when I specify --rerun-log-file, the state will be saved to the file, which is not the case (--rerun-update controls that.)

--rerun-update           If present the log file will be updated, otherwise it will be left unchanged

This is easily misread to be saying that if the log file is present it will be updated..
but otherwise it will be left unchanged? That doesn't make sense if you consider it logically, but parsing English sentences doesn't immediately engage my boolean logic module, so I've been confused this way more than once. The confusion could easily be avoided by avoiding the "if present" that's not immediately clear what it's referring to. 

It doesn't help that this option is what enables creating the log file if it doesn't exist yet,
despite the name suggesting it might only update the existing log file.

Something like: "specifying this option causes the log file to be updated to reflect the tests run, otherwise the log file will be left unchanged"

--rerun-filter ARG       A comma separated list to specify which tests to run when comparing against previous test runs.

The "when comparing" here is a very passive voice way to say that this option enables comparing against previous test runs. It would be clearer to say that specifying this option is what enables comparing against previous test runs, and that the list specifies which tests to compare.

Thanks for your consideration, and for the testing time this module saves!

**Comment by ocharles** [comment]
Hi @joeyh, thanks for the feedback. I think you're in the best position to suggest alternative documentation... would it be possible for you to paste an ideal output from `--help` here? I can do the work of actually adding that into the code.

**Comment by Bodigrim** [comment]
I did my best (_it wasn't much_), feel free to reopen if you come up with more suggestions.
