### ISSUE TITLE
Tagging releases on github

### ISSUE THREAD

**Issue by dvc94ch** [ocharles/tasty-rerun#9]
Hi,

For distro package maintainers it's nice to be able to quickly find the version of the source that we package from hackage. It's useful for applying bugfixes and security patches if needed. Doing a git blame on the version string doesn't tell us if the next commit is also part of the release without manually checking the changes.

Thank you,
David

**Comment by ocharles** [comment]
Hi David, I do tag releases (there are 5 tags here), but unfortunately I think a few versions might have slipped through the net. Sorry!
